name: App Build and Push

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build Application
      id: build_app
      run: mvn -B -DskipTests clean package --file pom.xml
#    - name: Login to Github Container Registry
#      id: docker_login
#      uses: docker/login-action@v1
#      with:
#        registry: ghcr.io
#        username: ${{ github.repository_owner }}
#        password: ${{ secrets.GCHR_PAT }}
    - name: Build and Push to GitHub Container Registry
      id: docker_build_push
      uses: docker/build-push-action@v2
      with:       
        push: true
        context: .
        file: ./src/main/docker/Dockerfile.jvm
        registry: ghcr.io
        tags: |
          kameshsampath/jo-quarkus-helloworld:latest
          kameshsampath/jo-quarkus-helloworld:master
    - name: Image digest
      run: echo ${{ steps.docker_build_push.outputs.digest }}
