name: App Build and Push

on:
  push:
    branches: [ master ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.0.3
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maven Build
        id: build_app
        run: mvn -B -DskipTests clean package --file pom.xml
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - uses: actions/upload-artifact@v2
        with:
          name: target
          path: target
  contianerBuild:
    runs-on: ubuntu-latest
    steps:
       - name: Download build target directory
         uses: actions/download-artifact@v2
         with:
          name: target
       - name: Build and Push to GitHub Container Registry
         id: docker_build_push
         uses: docker/build-push-action@v2
         with:
           push: true
           context: .
           file: ./src/main/docker/Dockerfile.jvm
           registry: ghcr.io
           tags: |
            kameshsampath/jo-quarkus-helloworld:latest
            kameshsampath/jo-quarkus-helloworld:master
       - name: Image digest
         run: echo ${{ steps.docker_build_push.outputs.digest }}
